### ISSUE TITLE
pacsift: exit 0 when package not found

### ISSUE THREAD

**Issue by coderobe** [andrewgregory/pacutils#22]
Much like https://github.com/andrewgregory/pacutils/issues/14, pacsift should probably also exit non-successfully when it doesn't find a match.

pacman does that as well.

```sh
$ pacsift --exact --name foobar
$ echo $?
0
$ pacman -Ss foobar
$ echo $?
1
```

**Comment by AladW** [comment]
Another example is when an invalid repo is specified to `pacsift` through `--repo`; it exits with 0 in that case as well.

**Comment by andrewgregory** [comment]
I'm reluctant to implement this as requested.  Non-zero exit values are already used to indicate fatal errors and I don't want to overload them to indicate empty results (which are not errors) as well.  Is 7fb838d608bdd3eae78213ac7f3a819e3cb28192 an acceptable alternative?

**Comment by coderobe** [comment]
I suppose that works too - though i think that makes it inconsistent with other pacutils programs (and pacman tooling in general, which makes heavy use of exit codes for signaling like this).

**Comment by andrewgregory** [comment]
Conformance with pacman is not a goal here.  Pacutils exists, in part, specifically because pacman does things in a way that makes scripting difficult.  How is this inconsistent with other pacutils programs?  I try to use non-zero exit values for fatal errors.  pacinfo returns non-zero if a package does not exist because its function is to print info about a package.  If that package does not exist, it cannot perform its function; hence that is a fatal error.  pacsift's function, on the other hand, is to search a set of packages.  If it successfully does that and ends up with an empty result set, that is a perfectly valid result.

**Comment by coderobe** [comment]
Good point.

**Comment by andrewgregory** [comment]
Merged.
